added saving of json blob

diff --git a/schema/fffile/merge-file-json b/schema/fffile/merge-file-json
--- a/schema/fffile/merge-file-json
+++ b/schema/fffile/merge-file-json
@@ -7,11 +7,11 @@
 #  Exit Status:
 #	0	ok, json blob produced
 #	1	blob does not exist
-#	2	wrong number of command line arguments
-#	3	blobio get failed
-#	4	command 'file --brief <blob> failed'
-#	5	blobio put json failed
-#	6	sql failed
+#	2	file output is not utf8
+#	3	wrong number of command line arguments
+#	4	blobio get failed
+#	5	command 'file --brief <blob> failed'
+#	6	blobio put json failed
 #  Environment:
 #	BLOBIO_SERVICE
 #	TMPDIR
@@ -30,28 +30,71 @@ die()
 	exit $STATUS
 }
 
-TMP_FILE=${TMPDIR:=/tmp}/$PROG.$$
+TMP_BLOB=${TMPDIR:=/tmp}/$PROG.blob.$$
+TMP_FILE=${TMPDIR:=/tmp}/$PROG.file.$$
+TMP_JSON=${TMPDIR:=/tmp}/$PROG.json.$$
+TMP_UTF8=${TMPDIR:=/tmp}/$PROG.utf8.$$
+
 leave()
 {
-	rm -f $TMP_FILE
+	rm -f $TMP_BLOB $TMP_FILE $TMP_JSON $TMP_UTF8
 }
 trap leave EXIT
 
-test $# = 1 || die 'wrong number of arguments' 2
+test $# = 1 || die 'wrong number of arguments' 3
 BLOB=$1
 
 #  fetch the blob
-blobio get --udig $BLOB --service $BLOBIO_SERVICE --output-path $TMP_FILE
+blobio get --udig $BLOB --service $BLOBIO_SERVICE --output-path $TMP_BLOB
 STATUS=$?
 test $STATUS = 1 && exit 1
-test $STATUS = 0 || die "blobio get failed: exit status=$STATUS" 3
+test $STATUS = 0 || die "blobio get failed: exit status=$STATUS" 4
 
 #  call 'file --brief'
-FILE_TYPE=$(file --brief $TMP_FILE)
-test $? = 0 || die "file --brief failed: exit status=$?"
+file --brief $TMP_BLOB >$TMP_FILE
+test $? = 0 || die "file command failed: exit status=$?" 5
 
-cat >$TMP_FILE <<END || die "cat tmp blob failed: exit status=$?" 5
+#  insure file output is proper utf8, which can be escaped
+FILE_TYPE='"'$(escape-json-utf8 <$TMP_FILE)'"'
+STATUS=$?
+case $STATUS in
+0)
+	EXIT_STATUS=0
+	;;
+1)
+	FILE_TYPE=null
+	EXIT_STATUS=2
+	;;
+*)
+	die "escape-json-utf8 failed: exit status=$STATUS" 5
+	;;
+esac
+
+#  build the json blob
+cat >$TMP_JSON <<END || die "cat >json failed: exit status=$?" 6
 {
-	"fffile.setspace
+	"fffile.setspace.com": {
+		"file": {
+			"blob": 	"$BLOB",
+			"file_type":	$FILE_TYPE
+		},
+		"date":		"$(date)",
+		"hostname":	"$(hostname)",
+		"env":	{
+			"USER":		"$USER"
+		},
+		"process_id":	$$
+	}
 }
-echo $FILE_TYPE
+END
+
+BLOB=$BLOBIO_ALGORITHM:$(
+	blobio eat							\
+		--input-path $TMP_JSON					\
+		--algorithm $BLOBIO_ALGORITHM
+)
+test $? = 0 || die "blobio eat failed: exit status=$?" 6
+
+blobio put --udig $BLOB --input-path $TMP_JSON --service $BLOBIO_SERVICE
+test $? = 0 || die "blobio put failed: exit status=$?" 6
+exit $EXIT_STATUS
