die() now redirects to stderr

diff --git a/find-schema b/find-schema
--- a/find-schema
+++ b/find-schema
@@ -17,7 +17,7 @@ PROG=$(basename $0)
 
 die()
 {
-	echo "$PROG: ERROR: $@"
+	echo "$PROG: ERROR: $@" >&2
 	exit 2
 }
 
