zapped creating run/ dir, exot 0 when no pid file

diff --git a/kill-flowd b/kill-flowd
--- a/kill-flowd
+++ b/kill-flowd
@@ -4,9 +4,8 @@
 #  Usage:
 #	kill-flowd <schema>
 #  Exit Status:
-#	0	running flowd process was killed
-#	1	flowd process was not running
-#	2	unknown error
+#	0	running flowd process was killed or process not running
+#	32	unexpected error
 #  Blame:
 #  	jmscott@setspace.com
 #  	setspace@gmail.com
@@ -19,6 +18,7 @@
 PROG=$(basename $0)
 
 #  pause after either stopping or starting flowd
+
 FLOWD_PAUSE=2
 
 log()
@@ -65,20 +65,14 @@ test -d "$SCHEMA_ROOT" || die "missing schema dir: $SCHEMA_ROOT"
 cd $SCHEMA_ROOT || die "cd $SCHEMA_ROOT failed: exit status=$?"
 test -e etc/profile && . etc/profile
 
-#  create the run directory and move on.
+test -d run || die "missing run directory: $(pwd)/run/"
 
-if [ ! -d run ];  then
-	WARN "creating run/ directory (ok): $(pwd)/run"
-	mkdir run || die "mkdir run failed: exit status=$?"
-	exit 1
-fi
-
-#  check for pid file for flowd process
+#  check for pid file of flowd process
 
 FLOWD_PID=run/flowd.pid
 if [ ! -e $FLOWD_PID ];  then
 	WARN "no pid file: $(pwd)/$FLOWD_PID"
-	exit 1
+	exit 0
 fi
 
 #  stop a possibly running flowd process
