finalize new launchd-flowd-init

diff --git a/launchd-flowd b/launchd-flowd
--- a/launchd-flowd
+++ b/launchd-flowd
@@ -49,12 +49,22 @@ test -n "$SETSPACE_ROOT" || die "environment var not defined: SETSPACE_ROOT"
 
 log "SETSPACE_ROOT=$SETSPACE_ROOT"
 log "flow file: $FLOW"
+log "current directory: $(pwd)"
+
+PID_PATH=run/flowd.pid
+if [ -e $PID_PATH ];  then
+	log "pid file exists: $PID_PATH"
+	zap-proc $PID_PATH  || die "zap-proc failed: exit status=$?"
+else
+	log "no stale flowd: $PID_PATH"
+fi
 
 #
 #  source in $SETSPACE_ROOT/etc/profile
 #
 
 PROFILE=$SETSPACE_ROOT/etc/profile
+log "source: $PROFILE"
 test -r $PROFILE || die "can not read setspace profile: $PROFILE"
 . $PROFILE || die "sourcing setspace profile failed: $PROFILE"
 
@@ -62,6 +72,7 @@ test -r $PROFILE || die "can not read setspace profile: $PROFILE"
 #  source in schema specific profile
 #
 PROFILE=etc/profile
+log "source: $PROFILE"
 test -r etc/profile || die "can not read schema profile: $PROFILE"
 . $PROFILE || die "sourcing schema profile failed: $PROFILE"
 
@@ -70,10 +81,12 @@ env | while read E;  do
 	log "$E"
 done
 
-if [ -x sbin/launchd-flow-init ];  then
-	log 'sbin/launchd-flow-init exists, so initializing ...'
-	sbin/launchd-flow-init						||
-		die "launchd-flow-init failed: exit status=$?"
+INITX=sbin/launchd-flowd-init
+if [ -x $INITX ];  then
+	log "$INITX exists, so initializing ..."
+	$INITX || die "launchd-flow-init failed: exit status=$?"
+else
+	log 'WARN (ok): $INITX does not exist'
 fi
 
 log "execing flowd server $FLOW ..."
