can specify particular schemas on command-line

diff --git a/rummy b/rummy
--- a/rummy
+++ b/rummy
@@ -1,20 +1,19 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 #  Synopsis:
-#	Find all blobs with known unknowns, across all schemas.
+#	Find all blobs with known unknowns, defaulting to all schemas
 #  Usage:
-#	rummy | cut -f2 | xargs bio-file
-#  Note:
-#		$ rummy
-#		libxml2\tsha:01871af3ae0a6af9096c3155c5741453b8eb83b8
-#		jsonorg\tsha:fef573f2fd3c76002e71f048c120abc0e0a3965f
+#	$ rummy | cut -f2 | xargs bio-file
 #
-#		$ rummy | cut -f2 | sort -u
+#	$ rummy
+#	libxml2\tsha:01871af3ae0a6af9096c3155c5741453b8eb83b8
+#	jsonorg\tsha:fef573f2fd3c76002e71f048c120abc0e0a3965f
 #
-#	letting the caller filter by schema.
+#	$ rummy | cut -f2 | sort -u
 #
 
 PROG=$(basename $0)
+trap '' PIPE
 
 die()
 {
@@ -22,22 +21,35 @@ die()
 	exit 1
 }
 
-test $# = 0 || die 'wrong number of arguments'
-
 test -n "$SETSPACE_ROOT" || die "env variable not defined: SETSPACE_ROOT"
 cd $SETSPACE_ROOT || die "cd $SETSPACE_ROOT failed"
 
-find-schema | while read SCH;  do
-	SQL=schema/$SCH/lib/rummy.sql
-	test -e $SQL || continue
-	psql								\
+psql_rummy()
+{
+	local SCH;
+	SCH=$1
+
+	psql -c "SELECT blob FROM $SCH.rummy;"				\
 		--tuples-only						\
-		--file $SQL						\
 		--no-psqlrc						\
 		--quiet							|
 	  sed '/^ *$/d'							|
 	  sed 's/ //g'							|
 	  sed "s/.*/$SCH	&/"
-STATUS=${PIPESTATUS[*]}
-test STATUS='0 0 0 0' || die "psql $SQL | sed failed: exit status=$STATUS"
+	STATUS=${PIPESTATUS[*]}
+
+	test "$STATUS" = '0 0 0 0'					||
+		die "psql rummy $SQL | sed failed: exit status=$STATUS"
+}
+
+if [ $# = 0 ];  then
+	find-schema | while read SCH;  do
+		psql_rummy $SCH || exit
+	done
+	exit 0
+fi
+
+while [ "$1" ];  do
+	psql_rummy "$1" || exit
+	shift
 done
