smarter about process state YETI/ZOMBI

diff --git a/run-stat-flowd-tuple b/run-stat-flowd-tuple
--- a/run-stat-flowd-tuple
+++ b/run-stat-flowd-tuple
@@ -60,16 +60,34 @@ if [ -e $FLOW_PATH ]; then
 	if [ -e $PID_PATH ];  then
 		if [ -s $PID_PATH ];  then
 			if stale-mtime $STALE_AFTER $PID_PATH;  then
-				STATE=YETI
+				_P=$(pgrep -F $PID_PATH >/dev/null)
+				STATUS=$?
+				case $STATUS in
+				0)
+					STATE=YETI
+					;;
+				1)
+					#  pgrep grumbles about a syntax error
+					#  in pidfile, yet still exits with
+					#  status 1.
+					test -n "$_P"			&&
+						die "pgrep failed: $_P"
+					STATE=ZOMBI
+					;;
+				*)
+					die "pgrep failed: exit status=$STATUS"\
+						"$_P"
+					;;
+				esac
 			else
 				STATE=UP
 			fi
 		else
-			STATE=YETI
+			STATE=ZOMBI		#  empty pid file
 		fi
 	else
 		STATE=DOWN
-		if [ -e $GYR_PATH ];  then
+		if [ -e $GYR_PATH ];  then	#  exit did not zap flowd.gyr
 			STATE=ZOMBI
 		fi
 	fi
