collapsed blobio/checker_255 into single exit status

diff --git a/schema/jsonorg/get-JSON_checker b/schema/jsonorg/get-JSON_checker
--- a/schema/jsonorg/get-JSON_checker
+++ b/schema/jsonorg/get-JSON_checker
@@ -5,10 +5,9 @@
 #  Exit Status:
 #	0	is valid json
 #	1	is not valid json
+#	2	blob does not exist
 #	3	wrong number of command line arguments
-#	4	blob does not exist
-#	5	error reading blob
-#	6	error invoking JSON_checker
+#	4	error reading blob or invoking JSON_checker
 #  Environment
 #	BLOBIO_SERVICE
 #  Usage:
@@ -31,7 +30,19 @@ test $# = 2 || die "wrong number of command line arguments" 3
 UDIG=$1
 SIZE=$2
 
-blobio get --udig "$UDIG" --service $BLOBIO_SERVICE |
-	merge-jsonb_255 "$UDIG" "$SIZE"
+blobio get --udig "$UDIG" --service $BLOBIO_SERVICE | JSON_checker
 STATUS=${PIPESTATUS[*]}
-echo "status: STATUS"
+case "$STATUS" in
+'0 0')
+	exit 0
+	;;
+'0 1')
+	exit 1
+	;;
+'1 '*)
+	exit 2
+	;;
+*)
+	die "blobio get | JSON_checker failed: exit status=$STATUS" 4
+	;;
+esac
