working flowd with new blob table

diff --git a/schema/jsonorg/upsert-jsonb_255 b/schema/jsonorg/upsert-jsonb_255
--- a/schema/jsonorg/upsert-jsonb_255
+++ b/schema/jsonorg/upsert-jsonb_255
@@ -3,10 +3,9 @@
 #   Synopsis:
 #   	Merge a json blob read on standard input into table jsonorg.jsonb_255.
 #   Usage:
-# 	 upsert-jsonb_255 <udig> <blob_size>
+# 	 upsert-jsonb_255 <udig>
 #   Arguments:
 #   	1	udig of the blob
-#   	2	size of the blob in bytes
 #   Exit Status:
 #   	0	ok, tuple was upserted
 #	1	blob does not exist
@@ -18,22 +17,23 @@
 PROG=upsert-jsonb_255
 
 BLOBIO_GET_SERVICE=${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}
-TMP_BLOB=${TMPDIR:=/tmp}/$PROG.$$
+TMP_BLOB=${TMPDIR:=/tmp}/$PROG-blob.$$
 
 die()
 {
-	source $SETSPACE_ROOT/schema/jsonorg/lib/upsert-fault.bash
-
-	die_upsert upsert_jsonb_255 $@
+	#source $SETSPACE_ROOT/schema/jsonorg/lib/upsert-fault.bash
+	#die_upsert upsert_jsonb_255 $@
+	echo "$PROG: ERROR: $@" >&2
+	exit 3
 }
 
 leave()
 {
-	rm -f $TMP_BLOB
+	rm --force $TMP_BLOB || echo "ERROR: rm tmp failed: exit status=$?" >&2
 }
 trap leave EXIT
 
-test $# = 2 || die "wrong number of arguments: got $#, expected 2" 2
+test $# = 1 || die "wrong number of arguments: got $#, expected 1"
 
 JSON_UDIG=$1
 SIZE=$2
@@ -46,13 +46,15 @@ STATUS=$?
 
 case $STATUS in
 0)
+	SIZE=$(stat --format '%s' $TMP_BLOB)
+	test $? = 0 || die "stat blob size failed: exit status=$?"
 	;;
 1)
 	exit 1
 	;;
 *)
-	die "blobio get failed: exit status=$STATUS" 3
+	die "blobio get failed: exit status=$STATUS"
 	;;
 esac
 upsert-stdin-jsonb_255 $JSON_UDIG $SIZE <$TMP_BLOB			||
-	die "upsert-stdin-jsonb_255 failed: exit status=$?" 4
+		die "upsert-stdin-jsonb_255 failed: exit status=$?"
