zapped json log

diff --git a/schema/pdfbox2/pddocument2pg b/schema/pdfbox2/pddocument2pg
--- a/schema/pdfbox2/pddocument2pg
+++ b/schema/pdfbox2/pddocument2pg
@@ -1,21 +1,22 @@
 #!/bin/bash
 #
 #  Synopsis:
-#	Extract the PDDocument scalars from PDF and store in json blob&pgdb.
+#	Extract the PDDocument scalars from PDF and merge into PostgreSQL
 #  Usage:
 #	json-pddocument2pg <udig>
 #  Exit Status:
-#	0	ok, extracted pddocument info and stored json blob
-#	1	pdf load failed
+#	0	ok, extracted pddocument info and stored into PostgreSQL
+#	1	pdf load failed (but still stored in PG)
 #	2	blob does not exist
 #	3	wrong number of arguments
-#	4	blobio error
-#	5	java putPDDocument failed
-#	6	save json error
-#	7	pg database error
+#	4	unexpected blobio error
+#	5	unexpected java putPDDocument failed
+#	6	pg database error
 #  Environment:
 #	BLOBIO_ALGORITHM=${BLOBIO_ALGORITHM:=sha}
 #	BLOBIO_SERVICE=${BLOBIO_SERVICE:=localhost:1797}
+#  Note:
+#	How do we know the output of putPDDocument is always UTF-8?
 #
 
 PROG=pddocument2pg
@@ -23,11 +24,10 @@ PROG=pddocument2pg
 TMP_BLOB=${TMP_DIR:=/tmp}/$PROG-$$.pdf
 TMP_ERR=${TMP_DIR:=/tmp}/$PROG-$$.err
 TMP_ROW=${TMP_DIR:=/tmp}/$PROG-$$.row
-TMP_JSON=${TMP_DIR:=/tmp}/$PROG-$$.json
 
 leave()
 {
-	rm -f $TMP_BLOB $TMP_ERR $TMP_ROW $TMP_JSON
+	rm -f $TMP_BLOB $TMP_ERR $TMP_ROW
 }
 trap leave EXIT
 
@@ -61,13 +61,18 @@ case $STATUS in
 	;;
 esac
 
-#  execute the java extract.  we expect only 0 and no stderr.
+#  execute the java extract.  although we expect only 0 and no stderr,
+#  0 with stderr is normal.  an exit status os 1 indicates a failed load
+#  of the pdf file.
+#  
 
 java -cp $CLASSPATH putPDDocument <$TMP_BLOB >$TMP_ROW 2>$TMP_ERR
 EXIT_STATUS=$?
 case $EXIT_STATUS in
 0)
 	#  pdf loaded and scalars extracted
+	#  Note: are we reading UTF-8?
+
 	read								\
 		NUMBER_OF_PAGES						\
 		DOCUMENT_ID						\
@@ -77,7 +82,8 @@ case $EXIT_STATUS in
 	<$TMP_ROW
 	;;
 1)
-	#  pdf load failed.
+	#  pdf load failed, but we merge a tuple anyway
+
 	NUMBER_OF_PAGES=null
 	DOCUMENT_ID=null
 	VERSION=null
@@ -86,11 +92,12 @@ case $EXIT_STATUS in
 	;;
 *)
 	#  unexpected java fault
+
 	if [ -s $TMP_ERR ];  then
-		ERROR "java stderr follows"
+		ERROR 'java stderr follows ...'
 		cat $TMP_ERR
 	else
-		ERROR "missing expected stderr from java"
+		ERROR 'missing expected stderr from java'
 	fi
 	die "java putPDDocument failed: exit status=$EXIT_STATUS" 5
 	;;
@@ -108,7 +115,7 @@ if [ -s $TMP_ERR ];  then
 	test $? = 0 || die "blobio eat stderr failed: exit status=$?" 4
 	UD=$BLOBIO_ALGORITHM:$D
 	blobio put --udig $UD --input-path $TMP_ERR --service $BLOBIO_SERVICE
-	test $? = 0 || die "blobio put stder failed: exit status=$?" 4
+	test $? = 0 || die "blobio put stderr failed: exit status=$?" 4
 	STDERR_BLOB="\"$UD\""
 	ERROR "stderr blob: $UD"
 	SQL_STDERR_BLOB="'$UD'"
@@ -117,41 +124,13 @@ else
 	SQL_STDERR_BLOB=null
 fi
 
-#  create a json record for the results of running pddocument
-cat >$TMP_JSON <<END || die "cat >json failed: exit status: $?" 6
-{
-	"pdfbox2.setspace.com": {
-		"putPDDocument": {
-			"blob":			"$UDIG",
-			"exit_status":		$EXIT_STATUS,
-			"number_of_pages":	$NUMBER_OF_PAGES,
-			"version":		$VERSION,
-			"is_all_security_to_be_removed":
-						$IS_ALL_SECURITY_TO_BE_REMOVED,
-			"is_encrypted":		$IS_ENCRYPTED,
-			"stderr_blob":		$STDERR_BLOB
-		},
-		"date":		"$(date)",
-		"hostname":	"$(hostname)",
-		"USER":		"$USER",
-		"process_id":	$$
-	}
-}
-END
-
-D=$(blobio eat --algorithm $BLOBIO_ALGORITHM --input-path $TMP_JSON)
-test $? = 0 || die "blobio eat failed: exit status=$?" 4
-blobio put 								\
-	--udig $BLOBIO_ALGORITHM:$D					\
-	--input-path $TMP_JSON						\
-	--service $BLOBIO_SERVICE
-test $? = 0 || die "blobio put failed: exit status=$?" 4
-
 #  merge the new tuple into the database
 
-psql --no-psqlrc --quiet <<END || die "psql insert failed: exit status=$?" 7
+psql --no-psqlrc --quiet <<EOF || die "psql insert failed: exit status=$?" 7
 
 \\set ON_ERROR_STOP on
+
+BEGIN TRANSACTION;
 
 INSERT INTO
   pdfbox2.pddocument(
@@ -177,6 +156,8 @@ DELETE FROM pdfbox2.pddocument_pending
   WHERE
   	blob = '$UDIG'
 ;
-END
+END TRANSACTION;
+
+EOF
 
 exit $EXIT_STATUS
