stable checkpoint of major refzctor with type setspace.udig

diff --git a/schema/fffile5/ssq-fffile5-ls b/schema/fffile5/ssq-fffile5-ls
--- a/schema/fffile5/ssq-fffile5-ls
+++ b/schema/fffile5/ssq-fffile5-ls
@@ -4,13 +4,18 @@
 #	script to invoke libexec/ssq-fffile5-ls-* scripts
 #  Exit Status:
 #	0	query ok, blob may of may not exists
+#  Note:
+#	Add duration to discover time!
 #
 PROG=$(basename $0)
 SQL=lib/$PROG.sql
+SQL_UDIG=lib/$PROG-udig.sql
 PSQL='psql
 	--expanded
 	--pset null=Unknown
 	--tuples-only
+	--no-psqlrc
+	--pset format=wrapped
 '
 
 die()
@@ -19,18 +24,18 @@ die()
 	exit 1
 }
 
-test $# = 1 || die "wrong count of cli args: got $#, want 1"
+if [ $# = 0 ];  then
+	$PSQL --file $SQL || die "psql ls failed: exit status=$?"
+	exit 0
+fi
 
-BLOB=$1
-shift
+if [[ "$1" =~ ^[a-z][a-z0-9]{0,7}:[[:graph:]]{32,128}$ ]];  then
+	LIBEXEC=libexec/$PROG-udig
+	test -x $LIBEXEC || die "no libexec: $LIBEXEC"
+	exec $LIBEXEC $@
+fi
 
-#
-#  Note:
-#	How do we know perl regex always enabled?
-#
-[[ $BLOB =~ ^[a-z][a-z0-9]{0,7}:[[:graph:]]{32,128}$ ]]			||
-				die "not a udig: $BLOB"
-	
-$PSQL --set blob=$BLOB --file $SQL || die "psql ls failed: exit stats=$?"
-
-exit 0
+ACTION=$1;  shift;
+LIBEXEC=$PROG-$ACTION
+test -x $LIBEXEC || die "unknown action: $ACTION"
+exec $LIBEXEC $@
