do not zap empty *.*dr files when KEPP_WROK_DIR=yes

diff --git a/schema/mydash/trace-blob-flow b/schema/mydash/trace-blob-flow
--- a/schema/mydash/trace-blob-flow
+++ b/schema/mydash/trace-blob-flow
@@ -86,9 +86,11 @@ fgrep_dr()
 		die "find | fgrep $DR_LOG failed: exit status=$STATUS"
 		;;
 	esac
-	test -s $DR_LOG							||
-		rm $DR_LOG						||
-		die "rm empty dr failed: exit status=$?"
+	if [ $KEEP_WORK_DIR = no ];  then
+		test -s $DR_LOG						||
+			rm $DR_LOG					||
+			die "rm empty dr failed: exit status=$?"
+	fi
 }
 
 find-schema | while read SCHEMA;  do
