quasi stable checkpoint merge with append-ftlx

diff --git a/schema/setops/upsert-flowd_command b/schema/setops/upsert-flowd_command
--- a/schema/setops/upsert-flowd_command
+++ b/schema/setops/upsert-flowd_command
@@ -3,11 +3,11 @@
 #  Synopsis:
 #	Merge commands in <schema>/etc/<schema>.flow in table flowd_command
 #  Usage:
-#	merge-flowd_schema <schema1> <schema2> ...
-#	echo "$SCHEMAs" | merge-flowd_schema
+#	upsert-flowd_schema <schema1> <schema2> ...
+#	echo "$SCHEMAs" | upsert-flowd_schema
 #  Exit Status:
-#	0	all schema merged
-#	1	unexpected error mering schema into db
+#	0	all schemas upserted into table flowd_schema
+#	1	unexpected error upserting schema into table
 #
 
 PROG=$(basename $0)
@@ -31,7 +31,7 @@ cd $SETSPACE_ROOT || die "cd SETSPACE_ROOT failed: exit status=$?"
 
 . etc/profile || die ". etc/profile failed: exit status=$?"
 
-merge_schema_command()
+upsert_schema_command()
 {
 	local SCHEMA=$1
 	local FLOW="schema/$SCHEMA/etc/$SCHEMA.flow"
@@ -46,7 +46,7 @@ merge_schema_command()
 			;;
 		esac
 
-		$PSQL <<END || die "psql merge failed: exit status=$?"
+		$PSQL <<END || die "psql upsert failed: exit status=$?"
 INSERT INTO setops.flowd_command (
 	schema_name,
 	command_name
@@ -60,14 +60,14 @@ END
 case $# in
 0)
 	while read SCH;  do
-		merge_schema_command $SCH				||
-			die "merge_schema_command failed: exit status=$?"
+		upsert_schema_command $SCH				||
+			die "upsert_schema_command failed: exit status=$?"
 	done
 	;;
 *)
 	for SCH in $@;  do
-		merge_schema_command $SCH				||
-			die "merge_flowd_command failed: exit status=$?"
+		upsert_schema_command $SCH				||
+			die "upsert_flowd_command failed: exit status=$?"
 	done
 	;;
 esac
diff --git a/schema/setops/upsert-flowd_schema b/schema/setops/upsert-flowd_schema
--- a/schema/setops/upsert-flowd_schema
+++ b/schema/setops/upsert-flowd_schema
@@ -3,11 +3,11 @@
 #  Synopsis:
 #	Merge a schema into table setops.flowd_schema
 #  Usage:
-#	merge-flowd_schema <schema1> <schema2> ...
-#	echo "$SCHEMAs" | merge-flowd_schema
+#	upsert-flowd_schema <schema1> <schema2> ...
+#	echo "$SCHEMAs" | upsert-flowd_schema
 #  Exit Status:
-#	0	all schema merged
-#	1	unexpected error mering schema into db
+#	0	all schemas upserted
+#	1	unexpected error merging schema into table flowd_schema
 #
 
 PROG=$(basename $0)
@@ -30,11 +30,11 @@ cd $SETSPACE_ROOT || die "cd SETSPACE_ROOT failed: exit status=$?"
 
 . etc/profile || die ". etc/profile failed: exit status=$?"
 
-merge_schema()
+upsert_schema()
 {
 	local SCHEMA=$1
 
-	$PSQL <<END || die "psql merge failed: exit status=$?"
+	$PSQL <<END || die "psql upsert failed: exit status=$?"
 INSERT INTO setops.flowd_schema (
 	schema_name
   ) VALUES('$SCHEMA')
@@ -47,12 +47,12 @@ END
 case $# in
 0)
 	while read SCH;  do
-		merge_schema $SCH || die "merge_schema failed: exit status=$?"
+		upsert_schema $SCH || die "upsert_schema failed: exit status=$?"
 	done
 	;;
 *)
 	for SCH in $@;  do
-		merge_schema $SCH || die "merge_schema failed: exit status=$?"
+		upsert_schema $SCH || die "upsert_schema failed: exit status=$?"
 	done
 	;;
 esac
