checkpont of new fltx code

diff --git a/schema/setcore/get-is-utf8wf b/schema/setcore/get-is-utf8wf
--- a/schema/setcore/get-is-utf8wf
+++ b/schema/setcore/get-is-utf8wf
@@ -15,44 +15,40 @@
 #	temporary file.
 #
 PROG=get-is-utf8wf
-BLOBIO_GET_SERVICE=${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}
-
-TMP_BLOB=${TMPDIR:=/tmp}/$PROG.$$
+SERVICE="--service ${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}"
+SQL=$SCHEMA_ROOT/lib
 
 die()
 {
-	echo "$PROG: ERROR: $1" >&2
+	echo "$PROG: ERROR: $@" >&2
 	exit 4
 }
 
-leave()
-{
-	rm --force $TMP_BLOB
-	exit
-}
-
-trap leave EXIT INT TERM QUIT
-
-test $# = 1 || die 'wrong number of arguments'
+test $# = 1 || die "wrong number of arguments: got $#, expected 1"
 BLOB=$1
+UDIG="--udig $BLOB"
+
+#  make work dir and change to that directory
+source $SETSPACE_ROOT/lib/work-dir.bash				||
+		die "source work-dir failed: exit status=$?"
 
 #  fetch the blob into temp file
 
-blobio get --service $BLOBIO_GET_SERVICE --udig $BLOB --output-path $TMP_BLOB
+blobio get $SERVICE $UDIG --output-path BLOB 2>STDERR
 STATUS=$?
 case $STATUS in
 0)
 	;;
 1)
-	blobio empty --udig $BLOB && exit 2
-	exit 3
+	exit 1
 	;;
 *)
 	die "blobio get failed: exit status=$STATUS"
 	;;
 esac
 
-is-utf8wf <$TMP_BLOB
+is-utf8wf <BLOB 2>STDERR
 STATUS=$?
 test $STATUS -gt 2 && die "is-utf8wf failed: exit status=$STATUS"
-exit $STATUS
+
+exit 0
diff --git a/schema/setcore/upsert-byte_bitmap b/schema/setcore/upsert-byte_bitmap
--- a/schema/setcore/upsert-byte_bitmap
+++ b/schema/setcore/upsert-byte_bitmap
@@ -10,10 +10,9 @@
 #  	2	unknown error
 #
 PROG=upsert-byte_bitmap
-SQL=lib/$PROG.sql
+SQL=$SCHEMA_ROOT/lib/$PROG.sql
 
-BLOBIO_GET_SERVICE=${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}
-TMP_BLOB=${TMPDIR:=/tmp}/$PROG.$$
+SERVICE="--service ${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}"
 PSQL='psql
 	--quiet
 	--no-psqlrc
@@ -22,25 +21,21 @@ PSQL='psql
 
 die()
 {
-	echo "$PROG: ERROR: $@" >&2
-	test -n "$BLOB" && setcore-fault $PROG $BLOB "$@"
+	setcore-fault upsert_byte_bitmap "$BLOB" "$@"
 	exit 2
 }
 
-leave()
-{
-	rm -f $TMP_BLOB
-	exit
-}
-
-trap leave EXIT INT TERM QUIT
-
 test $# = 1 || die "wrong number of arguments: got $#, expected 1"
 BLOB=$1
+UDIG="--udig $BLOB"
+
+#  make work dir and change to that directory
+source $SETSPACE_ROOT/lib/work-dir.bash				||
+		die "source work-dir failed: exit status=$?"
 
 #  fetch the blob into temp file
 
-blobio get --service $BLOBIO_GET_SERVICE --udig $BLOB --output-path $TMP_BLOB
+blobio get $SERVICE $UDIG --output-path BLOB 2>STDERR
 STATUS=$?
 case $STATUS in
 0)
@@ -53,9 +48,11 @@ case $STATUS in
 	;;
 esac
 
-HEX=$(byte-bitmap <$TMP_BLOB)
-test $? = 0 || die "byte-bitmap failed: exit status=$?"
-$PSQL --set blob=$BLOB --set hex=$HEX --file $SQL
-test $? = 0 || die "psql upsert failed: exit status=$?"
+HEX=$(byte-bitmap <BLOB 2>STDERR)
+STATUS=$?
+test $STATUS = 0 || die "byte-bitmap failed: exit status=$STATUS"
+
+$PSQL --set blob=$BLOB --set hex=$HEX --file $SQL			||
+			die "psql upsert failed: exit status=$?"
 
 exit 0
diff --git a/schema/setcore/upsert-byte_prefix_32 b/schema/setcore/upsert-byte_prefix_32
--- a/schema/setcore/upsert-byte_prefix_32
+++ b/schema/setcore/upsert-byte_prefix_32
@@ -16,31 +16,26 @@ PSQL='psql
 	--no-psqlrc
 	--no-readline
 '
-SQL=lib/$PROG.sql
-BLOBIO_GET_SERVICE=${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}
-
-TMP_BLOB=${TMPDIR:=/tmp}/$PROG.$$
+SQL=$SCHEMA_ROOT/lib/$PROG.sql
+SERVICE="--service ${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}"
 
 die()
 {
-	echo "$PROG: ERROR: $1" >&2
+	setcore-fault upsert_byte_prefix_32 "$BLOB" "$@"
 	exit 2
 }
 
-leave()
-{
-	rm -f $TMP_BLOB
-	exit
-}
-
-trap leave EXIT INT TERM QUIT
-
-test $# = 1 || die 'wrong number of arguments'
+test $# = 1 || die "wrong number of arguments: got $#, expected 1"
 BLOB=$1
+UDIG="--udig $BLOB"
+
+#  make work dir and change to that directory
+source $SETSPACE_ROOT/lib/work-dir.bash				||
+		die "source work-dir failed: exit status=$?"
 
 #  fetch the blob into temp file
 
-blobio get --service $BLOBIO_GET_SERVICE --udig $BLOB --output-path $TMP_BLOB
+blobio get $SERVICE $UDIG --output-path BLOB 2>STDERR
 STATUS=$?
 case $STATUS in
 0)
@@ -53,7 +48,7 @@ case $STATUS in
 	;;
 esac
 
-PREFIX=$(byte-prefix-32 <$TMP_BLOB)
+PREFIX=$(byte-prefix-32 <BLOB 2>STDERR )
 test $? = 0 || die "byte-prefix-32 failed: exit status=$?"
 
 #  merge new record
