moved fault processing to setcore.flow

diff --git a/schema/setcore/merge-byte_suffix_32 b/schema/setcore/merge-byte_suffix_32
--- a/schema/setcore/merge-byte_suffix_32
+++ b/schema/setcore/merge-byte_suffix_32
@@ -1,16 +1,13 @@
 #!/usr/bin/env bash
 #
 #  Synopsis:
-#	Merge the 32 byte suffix of the blob into the table byte_suffix_32
+#	Upsert the 32 byte suffix of the blob into the table byte_suffix_32
 #  Usage:
-#	merge-byte_suffix_32 <blob udig>
+#	upsert-byte_suffix_32 <blob udig>
 #  Exit Status:
-#  	0	suffix merged into table byte_suffix_32
+#  	0	suffix upserted into table byte_suffix_32
 #	1	blob does not exist
-#  	2	wrong number of command line arguments
-#	3	blobio get failed for unknown reason
-#	4	byte-suffix-32 failed for unknown reason
-#	5	sql merge failed for unknown reason
+#	2	unknown error
 #  Environment:
 #	BLOBIO_SERVICE
 #	BLOBIO_GET_SERVICE
@@ -20,18 +17,15 @@
 #	Consider pipelining blobs to eliminate dependence on TMPDIR.
 #
 
-PROG=merge-byte_suffix_32
+PROG=upsert-byte_suffix_32
 BLOBIO_GET_SERVICE=${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}
 
 TMP_BLOB=${TMPDIR:=/tmp}/$PROG.$$
 
 die()
 {
-	STATUS=$1
-	shift
-
 	echo "$PROG: ERROR: $@" >&2
-	exit $STATUS
+	exit 2
 }
 
 leave()
@@ -42,7 +36,7 @@ leave()
 
 trap leave EXIT INT TERM QUIT
 
-test $# = 1 || die 2 'wrong number of arguments'
+test $# = 1 || die 'wrong number of arguments'
 BLOB=$1
 
 #  fetch the blob into temp file
@@ -56,25 +50,25 @@ case $STATUS in
 	exit 1
 	;;
 *)
-	die 3 "blobio get failed: exit status=$STATUS"
+	die "blobio get failed: exit status=$STATUS"
 	;;
 esac
 
 PREFIX=$(byte-suffix-32 $TMP_BLOB)
-test $? = 0 || die 4 "byte-suffix-32 failed: exit status=$?"
+test $? = 0 || die "byte-suffix-32 failed: exit status=$?"
 
-#  merge new record
-psql --quiet --no-psqlrc <<END
+#  upsert new record
+psql --quiet --no-psqlrc --set blob=$BLOB <<END
 INSERT INTO setcore.byte_suffix_32 (
 	blob,
 	suffix
   ) VALUES (
-  	'$BLOB'::udig,
+  	:'blob'::udig,
 	E'\\\\x$PREFIX'
   ) ON CONFLICT
   	DO NOTHING
 ;
 END
-test $? = 0 || die 5 "psql insert failed: exit status=$?"
+test $? = 0 || die "psql insert failed: exit status=$?"
 
 exit 0
diff --git a/schema/setcore/merge-new_line_count b/schema/setcore/merge-new_line_count
--- a/schema/setcore/merge-new_line_count
+++ b/schema/setcore/merge-new_line_count
@@ -1,16 +1,13 @@
 #!/usr/bin/env bash
 #
 #  Synopsis:
-#	Merge the new-line count of a blob into the table new_line_count
+#	Upsert the new-line count of a blob into the table new_line_count
 #  Usage:
-#	merge-new_line_count <blob udig>
+#	upsert-new_line_count <udig>
 #  Exit Status:
-#  	0	count merged into table new_line_count
+#  	0	byte count upserted into table new_line_count
 #	1	blob does not exist
-#  	2	wrong number of command line arguments
-#	3	blobio get failed for unknown reason
-#	4	new-line-count failed for unknown reason
-#	5	sql merge failed for unknown reason
+#	2	unknown error
 #  Environment:
 #	BLOBIO_SERVICE
 #	BLOBIO_GET_SERVICE
@@ -19,7 +16,7 @@
 #  Note:
 #	Consider pipelining blobs to eliminate dependence on TMPDIR.
 #
-PROG=merge-new_line_count
+PROG=upsert-new_line_count
 BLOBIO_GET_SERVICE=${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}
 
 TMP_BLOB=${TMPDIR:=/tmp}/$PROG.$$
@@ -27,7 +24,7 @@ TMP_BLOB=${TMPDIR:=/tmp}/$PROG.$$
 die()
 {
 	echo "$PROG: ERROR: $1" >&2
-	exit $2
+	exit 2
 }
 
 leave()
@@ -38,7 +35,7 @@ leave()
 
 trap leave EXIT INT TERM QUIT
 
-test $# = 1 || die 'wrong number of arguments' 2
+test $# = 1 || die 'wrong number of arguments'
 BLOB=$1
 
 #  fetch the blob into temp file
@@ -52,24 +49,24 @@ case $STATUS in
 	exit 1
 	;;
 *)
-	die "blobio get failed: exit status=$STATUS" 3
+	die "blobio get failed: exit status=$STATUS"
 	;;
 esac
 
 COUNT=$(new-line-count <$TMP_BLOB)
-test $? = 0 || die "new-line-count failed: exit status=$?" 4
+test $? = 0 || die "new-line-count failed: exit status=$?"
 
-psql --quiet --no-psqlrc <<END
+psql --set blob=$BLOB --set count=$COUNT --quiet --no-psqlrc <<END
 INSERT INTO setcore.new_line_count (
 	blob,
 	line_count
   ) VALUES (
-  	'$BLOB'::udig,
-	$COUNT
+  	:'blob'::udig,
+	:'count'
   ) ON CONFLICT
   	DO NOTHING
 ;
 END
-test $? = 0 || die "psql insert failed: exit status=$?" 5
+test $? = 0 || die "psql insert failed: exit status=$?"
 
 exit 0
diff --git a/schema/setcore/upsert-byte_suffix_32 b/schema/setcore/upsert-byte_suffix_32
--- a/schema/setcore/upsert-byte_suffix_32
+++ b/schema/setcore/upsert-byte_suffix_32
@@ -1,11 +1,11 @@
 #!/usr/bin/env bash
 #
 #  Synopsis:
-#	Merge the 32 byte suffix of the blob into the table byte_suffix_32
+#	Upserted the 32 byte suffix of the blob into the table byte_suffix_32
 #  Usage:
-#	merge-byte_suffix_32 <blob udig>
+#	upsert-byte_suffix_32 <blob udig>
 #  Exit Status:
-#  	0	suffix merged into table byte_suffix_32
+#  	0	suffix upserted into table byte_suffix_32
 #	1	blob does not exist
 #  	2	unknown error
 #
@@ -21,7 +21,7 @@ SERVICE="--service ${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}"
 
 die()
 {
-	setcore-fault upsert_byte_suffix_32 "$BLOB" "$@"
+	echo "$PROG: ERROR: $@" >&2
 	exit 2
 }
 
@@ -52,7 +52,7 @@ SUFFIX=$(byte-suffix-32 BLOB 2>STDERR)
 STATUS=$?
 test $STATUS = 0 || die "byte-suffix-32 failed: exit status=$STATUS"
 
-#  merge new record
+#  upsert new record
 $PSQL --set blob=$BLOB --set suffix=$SUFFIX --file $SQL			||
 			die "psql upsert failed: exit status=$?"
 
