refactor of ssq

diff --git a/schema/setcore/ssq-setcore b/schema/setcore/ssq-setcore
--- a/schema/setcore/ssq-setcore
+++ b/schema/setcore/ssq-setcore
@@ -18,27 +18,12 @@ die()
 	exit 1
 }
 
-if [ $# = 0 ];  then
+ACTION="$1"
+if [ $# = 0 -o "$ACTION" = 'help' ];  then
 	help
 	exit 0
 fi
-ACTION=$1
-shift
+[[ "$ACTION" =~ ^service|ls|rummy$ ]] || die "unknown action: $ACTION"
 
-test -r etc/profile && . etc/profile
-
-case "$ACTION" in
-help|--help)
-	help
-	exit 0
-	;;
-service|ls|rummy)
-	;;
-*)
-	die "unknown action: $ACTION"
-	;;
-esac
-
-SCH_LIBEXEC=libexec/ssq-setcore-$ACTION
-test -x $SCH_LIBEXEC || die "no libexec for action '$ACTION'"
-exec $SCH_LIBEXEC $@
+. etc/profile || die "source etc/profile failed: exit status=$?"
+exec libexec/ssq-setcore-$ACTION $@
diff --git a/schema/setcore/ssq-setcore-ls b/schema/setcore/ssq-setcore-ls
--- a/schema/setcore/ssq-setcore-ls
+++ b/schema/setcore/ssq-setcore-ls
@@ -5,6 +5,14 @@
 #
 PROG=$(basename $0)
 
+PSQL='psql
+	--expanded
+	--tuples-only
+	--set=ON_ERROR_STOP=1
+	--no-psqlrc
+	--no-readline
+'
+
 help()
 {
 	echo "usage: $PROG [service|ls]"
@@ -16,7 +24,57 @@ die()
 	exit 1
 }
 
-test $# -eq 0 && exec libexec/ssq-setcore-ls-recent
+test $# -eq  0 || die "bad cli arg count:  got 0, want > 0"
 
-test $# -eq 1 || die "wrong cli args for ls blob: got $#, want 1"
-exec libexec/ssq-setcore-ls-blob "$1"
+while [ -n "$1" ];  do
+	BLOB="$1"
+	[[ $BLOB =~ ^[a-z][a-z0-9]{0,7}:[[:graph:]]{32,128}$ ]]		||
+					die "not a udig: $BLOB"
+	shift
+
+	$PSQL --set "blob=$BLOB" <<'END'				||\
+				die "psql ls failed: exit status=$?"
+SELECT
+	s.blob AS "Blob",
+	regexp_replace(age(now(), s.discover_time)::text, '\..*', '') || ' ago'
+                AS "Age",
+	pg_size_pretty(bc.byte_count) AS "Size",
+	CASE
+	  WHEN u8.is_utf8 IS NULL THEN
+	  	'Unknown'
+	  WHEN u8.is_utf8 THEN
+	  	'Yes'
+	  ELSE
+	  	'No'
+	END AS "UTF-8",
+	CASE
+	  WHEN p32.prefix IS NULL THEN
+	  	'Unknown'
+	  ELSE
+	  	encode(p32.prefix, 'escape')
+	END AS "32 Byte Prefix",
+	CASE
+	  WHEN s32.suffix IS NULL THEN
+	  	'Unknown'
+	  ELSE
+	  	encode(s32.suffix, 'escape')
+	END AS "32 Byte Suffix",
+	bb.bitmap::text AS "Byte Bitmap",
+	CASE
+	  WHEN rum.blob IS NULL THEN
+	  	'No'
+	  ELSE
+	  	'Yes'
+	END AS "Is Rummy"
+  FROM
+  	setcore.service s
+	  LEFT OUTER JOIN setcore.byte_count bc ON (bc.blob = s.blob)
+	  LEFT OUTER JOIN setcore.is_utf8wf u8 ON (u8.blob = s.blob)
+	  LEFT OUTER JOIN setcore.byte_prefix_32 p32 ON (p32.blob = s.blob)
+	  LEFT OUTER JOIN setcore.byte_suffix_32 s32 ON (s32.blob = s.blob)
+	  LEFT OUTER JOIN setcore.byte_bitmap bb ON (bb.blob = s.blob)
+	  LEFT OUTER JOIN setcore.rummy rum ON (rum.blob = s.blob)
+  WHERE
+  	s.blob = :'blob'
+END
+done
diff --git a/ssq b/ssq
--- a/ssq
+++ b/ssq
@@ -4,76 +4,40 @@
 #	Command line front end to sql queries for all schemas.
 #  Usage:
 #	ssq			#  help
-#	ssq ls			#  list all schemas
-#	ssq service <udig>	#  check of <schema>.service for udig
-#	ssq setcore help	#  help for "setcore" schema
-#	ssq jsonorg help	#  help for "jsonorg" schema
-#	ssq <schema> help	#  help for <schema>
-#  Note:
-#	In help() why are tabs aligned in vi but not in cat of message?
+#	ssq help		#  help
 #
 PROG=$(basename $0)
-
-die()
-{
-	cat >&2 <<END
-ERROR: $@
-usage: ssq [help | ls | service | [<schema>] [...options]]
-END
-	exit 1
-}
+USAGE="usage: $PROG [help | ls | <schema>"
 
 help()
 {
-	cat <<END
-Usage:
-	$PROG <schema> ...	#  query on a schema
-	$PROG <schema> help	#  help for queries on this schema
-	$PROG ls			#  list queryable schemas
-	$PROG service <udig>	#  trace a blob through schemas service tables
-
-	$PROG [help|--help]	#  ...
-END
+	echo "usage: $PROG [help | [<schema>] [...options]]"
 }
 
-#  help message
-if [ $# = 0 -o \( $# = 1 -a \( "$1" = help -o "$1" = --help \) \) ];  then
+die()
+{
+	echo "$PROG: ERROR: $@" >&2
 	help
-	exit 0
-fi
+	exit 1
+}
+
+ACTION="$1"
+[ $# -eq 0 -o "$ACTION" = help ] && exec echo $USAGE
+shift
 
 test -n "$SETSPACE_ROOT" || die "env not defined: SETSPACE_ROOT"
 cd $SETSPACE_ROOT || die "cd failed: $SETSPACE_ROOT"
-test -r etc/profile && . etc/profile
 
-ACTION="$1"
-shift
+#  list the schemas that support ssq
 
-case "$ACTION" in
-service|ls)
-	exec libexec/ssq-$ACTION $@
-	;;
-[a-z_]*)
-	;;
-*)
-	die "unknown action: $ACTION"
-	;;
-esac
+[ "$ACTION" = ls ] && exec libexec/ssq-ls $@
 
 SCHEMA=$ACTION
-SCHEMA_DIR=schema/$SCHEMA
-test -d $SCHEMA_DIR || die "not a schema: $SCHEMA"
-cd $SCHEMA_DIR || die "cd $SCHEMA_DIR/ failed: exit status=$?"
 
-#
-#  with no args ssq-<schema> runs ssq-<schema>-ls-recent
-#  schema
+test -d "schema/$SCHEMA" || die "unknown schema: $SCHEMA"
+cd schema/$SCHEMA || die "cd schema $SCHEMA failed; exit status=$?"
 
-if [ $# = 0 -a libexec/ssq-$SCHEMA-ls-recent ];  then
-	LS_RECENT=libexec/ssq-$SCHEMA-ls-recent
-	test -x $LS_RECENT && exec $LS_RECENT
-fi
-SCHEMA_EXEC=libexec/ssq-$SCHEMA
-test -e $SCHEMA_EXEC || die "no exec for schema: $SCHEMA"
-test -x $SCHEMA_EXEC || die "libexec not executable: $SCHEMA_EXEC"
-exec $SCHEMA_EXEC $@
+LIBEXEC="libexec/ssq-$SCHEMA"
+test -x $LIBEXEC || die "no ssq for schema: $SCHEMA"
+
+exec $LIBEXEC $@
