compressed all blobi exit status errors into status , renamed PDFBOX_JAR to PDFBOX2_JAR

diff --git a/schema/pdfbox/json-extract_utf8 b/schema/pdfbox/json-extract_utf8
--- a/schema/pdfbox/json-extract_utf8
+++ b/schema/pdfbox/json-extract_utf8
@@ -1,27 +1,24 @@
 #!/bin/bash
 #
 #  Synopsis:
-#	Extract UTF8 text from PDF and store results in json blob.
-#  Description:
-#	A well defined pdf file is fancy.
+#	Extract UTF8 text from proven PDF and store results in json blob.
 #  Usage:
 #	json-extract_utf8 <udig>
 #  Exit Status:
 #	0	extracted utf8 text and stored json blob
-#	1	text not extracted
-#	2	blob does not exist
-#	3	wrong number of arguments
-#	4	blobio get error
-#	5	blobio eat error
-#	6	java ExtractText failed
-#	7	json error
+#	1	blob does not exist
+#	2	wrong number of arguments
+#	3	PDFBOX2_JAR not defined or file does not exist
+#	4	blobio error
+#	5	json error
 #  Java Environment:
 #	The jar of pdfbox, version 2, must be in the CLASSPATH.
 #  Environment:
 #	BLOBIO_ALGORITHM=${BLOBIO_ALGORITHM:=sha}
 #	BLOBIO_SERVICE=${BLOBIO_SERVICE:=localhost:1797}
-#	PDFBOX_JAR
-
+#	PDFBOX2_JAR
+#  Note:
+#	Why can't "-jar $PDFBOX2_JAR" be replaced with CLASSPATH?
 #
 
 PROG=json-extract_utf8
@@ -47,6 +44,9 @@ die()
 test $# = 1 || die 'wrong number of arguments' 2
 UDIG=$1
 
+test -n "$PDFBOX2_JAR" || die "environment not defined: PDFBOX2_JAR" 3
+test -e $PDFBOX2_JAR || die "jar file does not exist: $PDFBOX2_JAR"
+
 #  fetch the pdf blob
 
 blobio get --udig $UDIG --output-path $TMP_BLOB --service $BLOBIO_SERVICE
@@ -58,14 +58,14 @@ case $STATUS in
 	exit 1
 	;;
 *)
-	die 'blobio get failed' 3
+	die 'blobio get failed' 4
 	;;
 esac
 
 put_file()
 {
 	FP=$1
-	if [ ! -r $FP ];  then
+	if [ ! -e $FP ];  then
 		echo null
 		return
 	fi
@@ -75,20 +75,20 @@ put_file()
 			--input-path $FP			\
 			--algorithm $BLOBIO_ALGORITHM		\
 	)
-	test $? = 0 ||  die "blobio eat failed: exit status=$?"
+	test $? = 0 ||  die "blobio eat failed: exit status=$?" 4
 	FILE_UDIG=$BLOBIO_ALGORITHM:$DIG
 	blobio put --udig $FILE_UDIG --input-path $FP --service $BLOBIO_SERVICE
-	test $? = 0 || die "blobio put failed: exit status=$?" 5
+	test $? = 0 || die "blobio put failed: exit status=$?" 4
 	echo '"'$FILE_UDIG'"'
 }
 
 #  execute the java extract.  we expect only 0 or 1 as an exit status
 
-java -jar $PDFBOX_JAR ExtractText $TMP_BLOB $TMP_UTF8 2>$TMP_ERR
+java -jar $PDFBOX2_JAR ExtractText $TMP_BLOB $TMP_UTF8 2>$TMP_ERR
 EXIT_STATUS=$?
 test $EXIT_STATUS = 0 && rm $TMP_ERR
 
-cat >$TMP_JSON <<END || die "cat >json failed: exit status: $?" 7
+cat >$TMP_JSON <<END || die "cat >json failed: exit status: $?" 5
 {
 	"pdfbox2.setspace.com": {
 		"extract_utf8": {
