improved exit status codes for iinvalid pdfs

diff --git a/schema/pdfbox/json-pddocument b/schema/pdfbox/json-pddocument
--- a/schema/pdfbox/json-pddocument
+++ b/schema/pdfbox/json-pddocument
@@ -1,23 +1,20 @@
 #!/bin/bash
 #
 #  Synopsis:
-#	Extract the PDDocument info from PDF and store results in json blob.
+#	Extract the PDDocument scalars from PDF and store results in json blob.
 #  Usage:
 #	json-pddocument <udig>
 #  Exit Status:
 #	0	ok, extracted pddocument info and stored json blob
-#	1	blob does not exist
-#	2	wrong number of arguments
-#	3	blobio get error
-#	4	java putPDDocument failed
-#	5	blobio eat error
-#	6	blobio put error
-#  Java Environment:
-#	The jar of pdfbox, version 2, must be in the CLASSPATH.
+#	1	pdf load failed
+#	2	blob does not exist
+#	3	wrong number of arguments
+#	4	blobio error
+#	5	java putPDDocument failed
+#	6	save json error
 #  Environment:
 #	BLOBIO_ALGORITHM=${BLOBIO_ALGORITHM:=sha}
 #	BLOBIO_SERVICE=${BLOBIO_SERVICE:=localhost:1797}
-#	PDFBOX_JAR
 #
 
 PROG=json-pddocument
@@ -35,11 +32,11 @@ trap leave EXIT
 die()
 {
 	STATUS=$2
-	echo "$PROG: ERROR: $@" >&2
+	echo "$PROG: ERROR: $1" >&2
 	exit $STATUS
 }
 
-test $# = 1 || die 'wrong number of arguments' 2
+test $# = 1 || die 'wrong number of arguments' 3
 UDIG=$1
 
 #  fetch the pdf blob
@@ -50,36 +47,49 @@ case $STATUS in
 0)
 	;;
 1)
-	exit 1
+	exit 2
 	;;
 *)
-	die 'blobio get failed' 3
+	die 'blobio get failed' 4
 	;;
 esac
 
 #  execute the java extract.  we expect only 0 and no stderr.
 
-java -jar $PDFBOX_JAR putPDDocument <$TMP_BLOB >$TMP_ROW 2>$TMP_ERR
+java -cp $CLASSPATH putPDDocument <$TMP_BLOB >$TMP_ROW 2>$TMP_ERR
 EXIT_STATUS=$?
-if [ $EXIT_STATUS != 0 -o -s $TMP_ERR ];  then
-	test -s $TMP_ERR && log "$PROG: ERROR: java stderr: $(cat $TMP_ERR)" >&2
-	test $EXIT_STATUS = 0 && WTF=' (wtf)'
-	die "java putPDDocument: exit status=$EXIT_STATUS$WTF" 4
-fi
-
-read 									\
-	NUMBER_OF_PAGES							\
-	DOCUMENT_ID							\
-	VERSION								\
-	IS_ALL_SECURITY_TO_BE_REMOVED					\
-	IS_ENCRYPTED							\
+case $EXIT_STATUS in
+0)
+	#  pdf loaded and scalars extracted
+	read								\
+		NUMBER_OF_PAGES						\
+		DOCUMENT_ID						\
+		VERSION							\
+		IS_ALL_SECURITY_TO_BE_REMOVED				\
+		IS_ENCRYPTED						\
 	<$TMP_ROW
+	;;
+1)
+	#  pdf load failed.
 
-cat >$TMP_JSON <<END || die "cat >json failed: exit status: $?" 7
+	NUMBER_OF_PAGES=null
+	DOCUMENT_ID=null
+	VERSION=null
+	IS_ALL_SECURITY_TO_BE_REMOVED=null
+	IS_ENCRYPTED=null
+	;;
+*)
+	test -s $TMP_ERR && log "$PROG: ERROR: java stderr: $(cat $TMP_ERR)" >&2
+	die "java putPDDocument failed: exit status=$EXIT_STATUS" 5
+	;;
+esac
+
+cat >$TMP_JSON <<END || die "cat >json failed: exit status: $?" 6
 {
 	"pdfbox2.setspace.com": {
 		"putPDDocument": {
 			"blob":			"$UDIG",
+			"exit_status":		$EXIT_STATUS,
 			"number_of_pages":	$NUMBER_OF_PAGES,
 			"version":		$VERSION,
 			"is_all_security_to_be_removed":
@@ -94,9 +104,10 @@ cat >$TMP_JSON <<END || die "cat >json failed: exit status: $?" 7
 END
 
 D=$(blobio eat --algorithm $BLOBIO_ALGORITHM --input-path $TMP_JSON)
-test $? = 0 || die "blobio eat failed: exit status=$?" 5
+test $? = 0 || die "blobio eat failed: exit status=$?" 4
 blobio put 								\
 	--udig $BLOBIO_ALGORITHM:$D					\
 	--input-path $TMP_JSON						\
 	--service $BLOBIO_SERVICE
-test $? = 0 || die "blobio put failed: exit status=$?" 6
+test $? = 0 || die "blobio put failed: exit status=$?" 4
+exit $EXIT_STATUS
