fixed error message formater

diff --git a/schema/pdfbox/json-extract_utf8 b/schema/pdfbox/json-extract_utf8
--- a/schema/pdfbox/json-extract_utf8
+++ b/schema/pdfbox/json-extract_utf8
@@ -35,7 +35,7 @@ trap leave EXIT
 die()
 {
 	STATUS=$2
-	echo "$PROG: ERROR: $@" >&2
+	echo "$PROG: ERROR: $1" >&2
 	exit $STATUS
 }
 
