unstable checkpoint

diff --git a/schema/pdfbox/merge-extract_pages_utf8 b/schema/pdfbox/merge-extract_pages_utf8
--- a/schema/pdfbox/merge-extract_pages_utf8
+++ b/schema/pdfbox/merge-extract_pages_utf8
@@ -3,20 +3,17 @@
 #  Synopsis:
 #	Extract all pages from pdf and merge into tables extract_page_utf8.
 #  Usage:
-#	merge-extract_pages_utf8 english <pdf blob>
 #	merge-extract_pages_utf8 <tsconfig> <pdf blob>
+#	merge-extract_pages_utf8 english sha:9611866f8547cbf7 ...
 #  Exit Status
-#	0	pages merged ok
-#	1	pdf blob not found
-#	2	program invocation or setup error
-#	3	unexpected blobio error
-#	4	java ExtractPagesUTF8.class failed
-#	5	sql error
+#  	0	ok, tuple was merged
+#	1	blob does not exist
+#	2	unexpected error
 #
 #  Environment:
 #	BLOBIO_SERVICE		#  required
 #	BLOBIO_GET_SERVICE
-#	BLOBIO_ALGORITHM
+#	BLOBIO_ALGORITHM	#  required
 #	TMPDIR
 #
 #  Java Classes:
@@ -25,59 +22,49 @@
 #	import org.apache.pdfbox.pdmodel.encryption.AccessPermission;
 #	import org.apache.pdfbox.text.PDFTextStripper;
 #  Note:
-#	The error status '0 3' in the loop over pages is not correct.
-#
-#	Page blobs may be orphaned if the transaction if aborted.
+#	Page blobs may be orphaned if the transaction is aborted.
 #	Perhaps a json blob summarizing the transaction should be created.
 #
 
-START_TIME=$(RFC3339Nano)
+START_EPOCH=$(date +%s)
 PROG=merge-extract_pages_utf8
-GET_SERVICE=${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}
+
+SERVICE=${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}
 WORK_DIR=${TMPDIR:=/tmp}/$PROG.$$.d
 ALGORITHM=${BLOBIO_ALGORITHM:=btc20}
-PSQL='psql --quiet --no-psqlrc'
+GET_SERVICE="--service ${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}"
 
 die()
 {
-	STATUS=$2
-	echo "$PROG: ERROR: $1" >&2
-	exit $STATUS
+	#  merge the error into 
+	if [ -n "$PDF_UDIG" ];  then
+		source $SETSPACE_ROOT/schema/pdfbox/lib/merge-fault.bash
+		die_merge merge_extract_pages_utf8 $@
+	fi
+	echo "$PROG: ERROR: $@" >&2
+	exit 2
 }
 
 leave()
 {
 	STATUS=$?
-	cd .. && rm -rf $WORK_DIR
+	cd .. && rm -rf "$WORK_DIR"
 	exit $STATUS
 }
 trap leave EXIT
+trap '' PIPE
 
-_fault()
-{
-	source $SETSPACE_ROOT/lib/fault-process.sh ||
-			die "source fault-process.sh failed: exit status=$?" 3
-	fault_process							\
-		pdfbox							\
-		extract_pages_utf8					\
-		$PDF_UDIG						\
-		"$TS_CONF: $1"						\
-		STDERR							\
-		$2							\
-		$START_TIME
-}
-
-test $# = 2 || die "wrong number of arguments: got $#, expected 2" 2
+test $# = 2 || die "wrong number of cli args: got $#, need 2"
 TS_CONF=$1
 PDF_UDIG=$2
 
-mkdir -p $WORK_DIR || die "mkdir work $WORK_DIR failed: exit status=$?" 2
-cd $WORK_DIR || die "cd work $WORK_DIR failed: exit status=$?" 2
+mkdir -p $WORK_DIR || die "mkdir work $WORK_DIR failed: exit status=$?"
+cd $WORK_DIR || die "cd work $WORK_DIR failed: exit status=$?"
 
 #  fetch the pdf blob into work directory
 
 PDF=$PDF_UDIG.pdf
-blobio get --udig $PDF_UDIG --output-path $PDF --service $GET_SERVICE
+blobio get --udig $PDF_UDIG --output-path $PDF $GET_SERVICE
 STATUS=$?
 
 case $STATUS in
@@ -87,7 +74,7 @@ case $STATUS in
 	exit 1
 	;;
 *)
-	die "blobio get pdf failed: exit status=$?" 3
+	die "blobio get pdf failed: exit status=$?"
 	;;
 esac
 
@@ -98,16 +85,16 @@ java 									\
 	-server								\
 	-cp $CLASSPATH							\
 	ExtractPagesUTF8						\
-	<$PDF 2>STDERR
+	<$PDF >STDOUT 2>STDERR
 STATUS=$?
+test $STATUS = 0 || die "java ExtractPagesUTF8 failed: exit status=$STATUS"
+test -e STDOUT || die "java write to stdout failed" 
 test -e STDERR || die "java write to stderr failed" 
-
-test $STATUS = 0 ||
-	_fault "java ExtractPagesUTF8 failed: exit status=$STATUS" 4
 
 #  loop through the page files to put the blobs and record udigs in <page>.udig
 
 find . -maxdepth 1 -name '[0-9][0-9][0-9][0-9][0-9][0-9][0-9].txt' -type f   |
+  sort									     |
   while read PAGE_PATH;  do
 
 	#  calculate the digest of the page of text
@@ -117,7 +104,7 @@ find . -maxdepth 1 -name '[0-9][0-9][0-9][0-9][0-9][0-9][0-9].txt' -type f   |
 			--input-path $PAGE_PATH				\
 			--algorithm $ALGORITHM
 	)
-	test $? = 0 || die "blobio eat page text failed: exit status=$?" 3
+	test $? = 0 || die "blobio eat page text failed: exit status=$?"
 
 	#  put the page of text to blob storage
 
@@ -125,28 +112,38 @@ find . -maxdepth 1 -name '[0-9][0-9][0-9][0-9][0-9][0-9][0-9].txt' -type f   |
 		--input-path $PAGE_PATH					\
 		--udig $PAGE_UDIG					\
 		--service $BLOBIO_SERVICE				||
-		die "blobio put page failed: exit status=$?" 3
+		die "blobio put page failed: exit status=$?"
 
 	UDIG_PATH=$(basename $PAGE_PATH .txt).udig
 	echo $PAGE_UDIG >$UDIG_PATH ||
-				die "echo udig > failed: exit status=$?" 2
+				die "echo page udig > failed: exit status=$?"
+
+	#  Note: blob must appear in setcore.service or foreign key fails!
+
+	spin-wait-blob setcore.service blob 32 $PAGE_UDIG
+	STATUS=$?
+	case $STATUS in
+	0)
+		;;		#  blob appeared in table setcore.service
+	1)
+		die 'spin-wait-blob: page txt: blob not in setcore.service'
+		;;
+	*)
+		die "spin-wait-blob failed: exit status=$STATUS"
+		;;
+	esac
+		
 done
 STATUS=${PIPESTATUS[*]}
 case "$STATUS" in
-'0 0')
-	;;
-'0 2')
-	exit 2
-	;;
-'0 3')
-	exit 3		# WTF?
+'0 0 0')
 	;;
 *)
-	die "find | page text failed: exit status=$STATUS" 2
+	die "find | page text failed: exit status=$STATUS"
 	;;
 esac
 
 #  sql merge all pages, text, tsf in database in a single transaction
 
-merge-all-extract_pages_utf8 $PDF_UDIG $TS_CONF 2>STDERR ||
-	_fault "merge-all-extract_pages_utf8 failed: exit status=$?" 5
+merge-all-extract_pages_utf8 "$TS_CONF" $PDF_UDIG 2>STDERR ||
+	die "merge-all-extract_pages_utf8 failed: exit status=$?"
diff --git a/schema/pdfbox/merge-pddocument b/schema/pdfbox/merge-pddocument
--- a/schema/pdfbox/merge-pddocument
+++ b/schema/pdfbox/merge-pddocument
@@ -6,71 +6,53 @@
 #	merge-pddocument <udig>
 #  Exit Status:
 #	0	ok, extracted pddocument info and stored into PostgreSQL
-#	1	blob does not exist
+#	1	pdf blob does not exist
 #	2	unexpected error
 #  Environment:
 #	BLOBIO_SERVICE
 #	BLOBIO_GET_SERVICE
 #	TMPDIR
 #  Note:
+#	Need to insure putPDDocument always writes utf8 and not utf16!
+#
 #	Need to merge fault into flow file, instead of in this script.
 #
 
-START_EPOCH=$(date +%s)
 PROG=merge-pddocument
-PSQL='psql --no-psqlrc --quiet'
-
+PSQL='psql --no-psqlrc --quiet --no-readline --set=ON_ERROR_STOP=1'
 SERVICE="--service ${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}"
-TMPDIR=${TMPDIR:=/tmp}
-WORK_DIR=$TMPDIR/$PROG-$$.d
-
-TMP_BLOB=$WORK_DIR/BLOB
-TMP_ROW=$WORK_DIR/ROW
+WORK_DIR=${TMPDIR:=/tmp}/$PROG-$$.d
 
 leave()
 {
-	rm -fr $WORK_DIR
+	rm -fr "$WORK_DIR"						||
+		echo "$PROG: ERROR: rm work dir failed: exit status=$?" >&2
 }
 
 die()
 {
-	local STATUS=$2
-
-	local MSG="$PROG: ERROR: $1"
-	echo $MSG >&2
-
-	#
-	#  Best effort to get all of stderr into setcore fault table
-	#
-	(
-		echo $MSG
-		if [ -d "$WORK_DIR" && -s STDERR ];  then
-			cat STDERR >&2
-			cat STDERR
-		fi
-	) | merge-stdin-fault_flow_call					\
-		pdfbox merge_pddocument	$UDIG ERR $STATUS 0
-
-	#  reset exit status if fault INSERT fails
-
-	local PSTATUS=${PIPESTATUS[*]}
-	if [ "$PSTATUS" != '0 0' -a $STATUS = 0 ];  then
-		STATUS=3
-	fi
-	exit $STATUS
+	source $SETSPACE_SCHEMA_ROOT/lib/merge-fault.bash
+	die_merge merge_pddocument $@
 }
 
+jdie()
+{
+	die "java putPDDocument: $@"
+}
+
+test $# = 1 || die "wrong number of arguments: got $#, need 1"
+PDF_UDIG=$1
+UDIG="--udig $PDF_UDIG"
+
 trap leave EXIT
-test $# = 1 || die "wrong number of arguments: got $#, expected 1" 3
-BLOB=$1
-UDIG="--udig $BLOB"
+trap '' PIPE
 
 mkdir $WORK_DIR || die "mkdir failed: $WORK_DIR"
 cd $WORK_DIR || die "cd work dir failed: exit status=$?"
 
 #  fetch the pdf blob
 
-blobio get $UDIG $SERVICE --output-path $TMP_BLOB
+blobio get $UDIG $SERVICE --output-path BLOB
 STATUS=$?
 case $STATUS in
 0)
@@ -79,22 +61,42 @@ case $STATUS in
 	exit 1
 	;;
 *)
-	die "blobio get pdf failed: exit status=$?" 3
+	die "blobio get pdf failed: exit status=$?"
 	;;
 esac
 
 #  execute the java extract.  although we expect only 0 and no stderr,
-#  0 with stderr is normal for pdfbox.
-#  an exit status of 1 indicates a failed load of the pdf file.
+#  0 with output to stderr is normal for pdfbox.
+#  an exit status of 1 indicates a failed load of the pdf file
 
-java -server -cp $CLASSPATH putPDDocument <$TMP_BLOB >$TMP_ROW 2>$TMP_STDERR
+java -server -cp $CLASSPATH putPDDocument <BLOB >ROW 2>STDERR
 STATUS=$?
-
 #  insure at least file STDERR exists
-test -e STDERR || die "write to temp failed: $TMP_STDERR"
+
+test -e STDERR || die "write to temp failed: STDERR"
+test -e ROW || die "write to temp failed: ROW"
+
+case $STATUS in
+0)
+	;;
+2)
+	jdie 'load of pdf failed: exit status=2'
+	;;
+3)
+	jdie 'invocation error: exit status=3'
+	;;
+4)
+	jdie 'unexpected java exception: exit status=4'
+	;;
+*)
+	jdie "impossible java exit status: $STATUS"
+	;;
+esac
+
 test $STATUS = 0							||
-	die "java putPDDocument failed: exit status=$STATUS"
-	
+	die "putPDDocument failed: exit status=$STATUS"
+test -s ROW || die 'ROW of putPDDocument is empty'
+
 #
 #  pdf loaded and scalars extracted
 #
@@ -108,9 +110,9 @@ read								\
 	VERSION							\
 	IS_ALL_SECURITY_TO_BE_REMOVED				\
 	IS_ENCRYPTED						\
-<$TMP_ROW
+<ROW
 
-$PSQL <<EOF || die "psql insert failed: exit status=$?" 7
+$PSQL <<EOF || die "psql insert failed: exit status=$?"
 
 INSERT INTO
   pdfbox.pddocument(
@@ -121,7 +123,7 @@ INSERT INTO
 	is_all_security_to_be_removed,
 	is_encrypted
     ) VALUES (
-    	'$UDIG',
+    	'$PDF_UDIG',
 	$NUMBER_OF_PAGES,
 	$DOCUMENT_ID,
 	$VERSION,
diff --git a/schema/pdfbox/merge-pddocument_information b/schema/pdfbox/merge-pddocument_information
--- a/schema/pdfbox/merge-pddocument_information
+++ b/schema/pdfbox/merge-pddocument_information
@@ -6,15 +6,9 @@
 #	merge-pddocument_information <udig>
 #  Exit Status:
 #	0	ok, extracted pddocument info and stored into PostgreSQL
-#	1	pdf load ok but some fields do not satify database constraints.
-#	2	pdf load failed
-#	3	blob does not exist
-#	4	script invocation or setup error
-#	5	unexpected blobio error
-#	6	unexpected java putPDDocument failed
-#	7	pg database error
+#	1	blob does not exist
+#	2	unexpected error
 #  Environment:
-#	BLOBIO_ALGORITHM
 #	BLOBIO_SERVICE
 #	BLOBIO_GET_SERVICE
 #	TMPDIR
@@ -22,60 +16,53 @@
 #	How do we know the output of putPDDocumentInformation is always UTF-8?
 #
 
-START_TIME=$(RFC3339Nano)
 PROG=merge-pddocument_information
-PSQL='psql --no-psqlrc --quiet'
-BLOBIO_GET_SERVICE=${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}
-ALGORITHM=${BLOBIO_ALGORITHM:=btc20}
+PSQL='psql --no-psqlrc --quiet --no-readline'
+SERVICE="--service ${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}"
 
-TMP_BLOB=${TMPDIR:=/tmp}/$PROG-$$.pdf
-TMP_STDERR=${TMPDIR:=/tmp}/$PROG-$$.err
-TMP_ROW=${TMPDIR:=/tmp}/$PROG-$$.row
+WORK_DIR=${TMPDIR:=/tmp}/$PROG-$$.d
 
 leave()
 {
-	STATUS=$?
-	rm -f $TMP_BLOB $TMP_STDERR $TMP_ROW
-	exit $STATUS
+	true
+	#rm --recursive --force $WORK_DIR				||
+		#echo "$PROG: ERROR: rm work dir failed: exit status=$?" >&2
 }
+
 trap leave EXIT
+trap '' PIPE
 
 die()
 {
-	STATUS=$2
-	echo "$PROG: ERROR: $1" >&2
-	exit $STATUS
+	source $SETSPACE_SCHEMA_ROOT/lib/merge-fault.bash
+	die_merge merge_pddocument_information $@
 }
 
-_fault()
+jdie()
 {
-	source $SETSPACE_ROOT/lib/fault-process.sh ||
-			die "source fault-process.sh failed: exit status=$?" 3
-	fault_process							\
-		pdfbox							\
-		pddocument_information					\
-		$UDIG							\
-		"$1"							\
-		$TMP_STDERR						\
-		$2							\
-		$START_TIME
+	die "java putPDDocumentInformation failed: $@"
 }
 
-test $# = 1 || die "wrong number of arguments: got $#, expected 1" 4
-UDIG=$1
+test $# = 1 || die "wrong number of arguments: got $#, need 1"
+PDF_UDIG=$1
+
+mkdir $WORK_DIR || die "mkdir work failed: exit status=$?"
+cd $WORK_DIR || die "cd work dir failed: exit status=$?"
+
+UDIG="--udig $PDF_UDIG"
 
 #  fetch the pdf blob
 
-blobio get --udig $UDIG --output-path $TMP_BLOB --service $BLOBIO_GET_SERVICE
+blobio get $UDIG $SERVICE --output-path BLOB
 STATUS=$?
 case $STATUS in
 0)
 	;;
 1)
-	exit 3
+	exit 1
 	;;
 *)
-	die "blobio get pdf failed: exit status=$STATUS" 5
+	die "blobio get pdf failed: exit status=$STATUS"
 	;;
 esac
 
@@ -83,26 +70,33 @@ esac
 #  0 with stderr is normal.  an exit status of 3 indicates a failed load
 #  of the pdf file.
 
-java <$TMP_BLOB								\
+java <BLOB								\
 	-server								\
 	-cp $CLASSPATH putPDDocumentInformation 			\
-	>$TMP_ROW 2>$TMP_STDERR
+	>ROW 2>STDERR
 STATUS=$?
-test -e $TMP_STDERR || die "java write to stderr failed" 4
+test -e STDERR || die 'java write to stderr failed'
+test -e ROW || die 'java write to row failed'
+
 case $STATUS in
 0)
-	EXIT_STATUS=0
 	;;
 2)
-	EXIT_STATUS=1
+	jdie 'violation of db constraints: exit status=2'
 	;;
-*)
-	_fault "java putPDDocumentInformation failed: exit status=$STATUS" 6
+3)
+	jdie 'load of pdf failed: exit status=3'
+	;;
+4)
+	jdie 'invocation failed: exit status=4'
+	;;
+5)
+	jdie 'unexpected java error: exit status=5'
 	;;
 esac
 
 merge-stdin-pddocument_information					\
-	$UDIG								\
-	$(file-stat-size $TMP_ROW) <$TMP_ROW				||
-	die "merge-stdin-pddocument_information failed: exit status=$?" 7
-exit $EXIT_STATUS
+	$PDF_UDIG							\
+	$(file-stat-size ROW) <ROW					||
+	die "merge-stdin-pddocument_information failed: exit status=$?"
+exit 0
diff --git a/schema/setops/merge-flowd_call_fault b/schema/setops/merge-flowd_call_fault
--- a/schema/setops/merge-flowd_call_fault
+++ b/schema/setops/merge-flowd_call_fault
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 #
 #  Synopsis:
-#	Merge fault for a flowd call
+#	Merge fault for a flowd call.
 #  Usage:
 #	merge-flowd_call_fault						\
 #		pdfbox							\
@@ -17,7 +17,13 @@
 #  Exit Status:
 #	0	fault merged into table setops.flowd_call_fault
 #	1	unexpected error (no fault written)
+#  Note:
+#	Would be nice to eliminate the spin-wait-blob code.  Without the code
+#	the std{out,err} can not reference setcore.service.
 #
+
+set -x
+
 PROG=$(basename $0)
 PSQL='psql --no-psqlrc --quiet --no-readline'
 export TMP_INPUT_PATH
@@ -29,7 +35,7 @@ leave()
 
 die()
 {
-	echo "ERROR: $@" >&2
+	echo "$PROG: ERROR: $@" >&2
 	exit 1
 }
 
@@ -62,6 +68,7 @@ eat() {
 	case "$SRC_PATH" in
 	-)
 		TMP_INPUT_PATH=${TMPDIR:=/tmp}/$PROG-$WHAT-$$.blob
+
 		#  slurp stdin for for stderr
 		cat >$TMP_INPUT_PATH || die "cat >$WHAT failed: exit status=$?"
 		SRC_PATH=$TMP_INPUT_PATH
@@ -86,7 +93,18 @@ eat() {
 }
 
 STDOUT_BLOB=$(eat stdout $STDOUT_PATH)
-STDERR_BLOB=$(eat stdout $STDERR_PATH)
+STDERR_BLOB=$(eat stderr $STDERR_PATH)
+
+#
+#  Note:
+#	wait for std{out,err} blobs to appear in table setcore.service;
+#	otherwise, the foreign key reference in flowd_call-fault causes
+#	INSERT to fail.  Seems like a better way should exist.
+#
+spin-wait-blob setcore.service blob 32 $STDOUT_BLOB			||
+			die "spin-wait-blob stdout failed: exit status=$?: $"
+spin-wait-blob setcore.service blob 32 $STDERR_BLOB			||
+			die "spin-wait-blob stderr failed: exit status=$?"
 
 $PSQL <<END || die "psql insert failed: exit status=$?"
 INSERT INTO setops.flowd_call_fault(
