checkpoint for broken merge-stdin-pddocument_information

diff --git a/schema/pdfbox/merge-pddocument b/schema/pdfbox/merge-pddocument
--- a/schema/pdfbox/merge-pddocument
+++ b/schema/pdfbox/merge-pddocument
@@ -48,7 +48,7 @@ ERROR()
 	echo "$PROG: ERROR: $@" >&2
 }
 
-test $# = 1 || die "wrong number of arguments: expected 1 got $#" 3
+test $# = 1 || die "wrong number of arguments: got $#, expected 1" 3
 UDIG=$1
 
 #  fetch the pdf blob
@@ -98,7 +98,7 @@ INSERT INTO pdfbox.fault_pddocument (
 	DO NOTHING
 ;
 END
-	test $EXIT_STATUS != 2 || die "java failed: exit status=$?" 5
+	test $EXIT_STATUS = 2 || die "java failed: exit status=$EXIT_STATUS" 5
 	exit 1
 fi
 
diff --git a/schema/pdfbox/merge-pddocument_information b/schema/pdfbox/merge-pddocument_information
--- a/schema/pdfbox/merge-pddocument_information
+++ b/schema/pdfbox/merge-pddocument_information
@@ -6,13 +6,13 @@
 #	merge-pddocument <udig>
 #  Exit Status:
 #	0	ok, extracted pddocument info and stored into PostgreSQL
-#	1	pdf load failed (but still stored in PG)
+#	1	pdf load failed
 #	2	blob does not exist
-#	3	wrong number of arguments
+#	3	invocation error
 #	4	unexpected blobio error
 #	5	unexpected java putPDDocument failed
 #	6	pg database error
-#	7	field in metadata contained a new-line
+#	7	infomation data violates database constraint
 #  Environment:
 #	BLOBIO_ALGORITHM
 #	BLOBIO_SERVICE
@@ -24,14 +24,16 @@
 
 PROG=merge-pddocument_information
 BLOBIO_GET_SERVICE=${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}
+ALGORITHM=${BLOBIO_ALGORITHM:=bc160}
 
 TMP_BLOB=${TMPDIR:=/tmp}/$PROG-$$.pdf
-TMP_ERR=${TMPDIR:=/tmp}/$PROG-$$.err
-TMP_FIELD=${TMPDIR:=/tmp}/$PROG-$$.row
+TMP_STDERR=${TMPDIR:=/tmp}/$PROG-$$.err
+TMP_ROW=${TMPDIR:=/tmp}/$PROG-$$.row
 
 leave()
 {
-	rm -f $TMP_BLOB $TMP_ERR $TMP_FIELD
+	#rm -f $TMP_BLOB $TMP_STDERR $TMP_ROW
+	true
 }
 trap leave EXIT
 
@@ -47,7 +49,7 @@ ERROR()
 	echo "$PROG: ERROR: $@" >&2
 }
 
-test $# = 1 || die 'wrong number of arguments' 3
+test $# = 1 || die "wrong number of arguments: got $#, expected 1" 3
 UDIG=$1
 
 #  fetch the pdf blob
@@ -69,109 +71,37 @@ esac
 #  0 with stderr is normal.  an exit status of 1 indicates a failed load
 #  of the pdf file.
 
-java -cp $CLASSPATH putPDDocument <$TMP_BLOB >$TMP_FIELD 2>$TMP_ERR
+java -cp $CLASSPATH putPDDocumentInformation <$TMP_BLOB >$TMP_ROW 2>$TMP_STDERR
 EXIT_STATUS=$?
-case $EXIT_STATUS in
-0)
-	#  pdf loaded and scalars extracted
-	#  Note: are we reading UTF-8?
+test -e $TMP_STDERR || die "java write to stderr failed" 5
+cat $TMP_STDERR >&2
 
-	read								\
-		NUMBER_OF_PAGES						\
-		DOCUMENT_ID						\
-		VERSION							\
-		IS_ALL_SECURITY_TO_BE_REMOVED				\
-		IS_ENCRYPTED						\
-	<$TMP_FIELD
-	;;
-1)
-	#  pdf load failed, but we merge a tuple anyway
-
-	NUMBER_OF_PAGES=null
-	DOCUMENT_ID=null
-	VERSION=null
-	IS_ALL_SECURITY_TO_BE_REMOVED=null
-	IS_ENCRYPTED=null
-	;;
-*)
-	#  unexpected java fault
-
-	if [ -s $TMP_ERR ];  then
-		ERROR 'java stderr follows ...'
-		cat $TMP_ERR
-	else
-		ERROR 'missing expected stderr from java'
-	fi
-	die "java putPDDocument failed: exit status=$EXIT_STATUS" 5
-	;;
-esac
-
-#  pddocument succeeded (although pdf may be unloadable),
-#  so a tuple will be merged into PostgreSQL.
-#  log any stderr to our stderr for easy debugging.
-
-if [ -s $TMP_ERR ];  then
-	ERROR 'java pdf load failed (ok), stderr follows'
-	cat $TMP_ERR
-
-	#  get the digest of stderr output file
-
-	D=$(
-		blobio eat						\
-			--algorithm $BLOBIO_ALGORITHM			\
-			--input-path $TMP_ERR
+if [ $EXIT_STATUS != 0 ];  then
+	STDERR_UDIG=$ALGORITHM:$(
+		blobio eat --algorithm $ALGORITHM --input-path $TMP_STDERR
 	)
-	test $? = 0 || die "blobio eat stderr failed: exit status=$?" 4
-
-	#  put the standard error blob
-
-	UD=$BLOBIO_ALGORITHM:$D
-	blobio put --udig $UD --input-path $TMP_ERR --service $BLOBIO_SERVICE
-	test $? = 0 || die "blobio put stderr failed: exit status=$?" 4
-
-	#  record for the write to the table.
-	STDERR_BLOB="\"$UD\""
-	ERROR "stderr blob: $UD"
-	SQL_STDERR_BLOB="'$UD'"
-else
-	STDERR_BLOB=null
-	SQL_STDERR_BLOB=null
+	blobio put							\
+		--udig $STDERR_UDIG					\
+		--input-path $TMP_STDERR				\
+		--service $BLOBIO_SERVICE				||
+		die "blobio put stderr failed: exit status=$?" 4
+	$PSQL <<END || die "psql insert fault failed: exit status=$?" 6
+INSERT INTO pdfbox.fault_pddocument_information (
+	blob,
+	exit_status,
+	stderr_blob
+) VALUES (
+	'$UDIG',
+	$EXIT_STATUS,
+	'$STDERR_UDIG'
+)
+END
+	test $EXIT_STATUS = 2 || die "java failed: exit status=$EXIT_STATUS" 5
+	exit 1
 fi
 
-#  merge the new tuple into the database
-
-psql --no-psqlrc --quiet <<EOF || die "psql insert failed: exit status=$?" 7
-
-\\set ON_ERROR_STOP on
-
-BEGIN TRANSACTION;
-
-INSERT INTO
-  pdfbox.pddocument(
-  	blob,
-	exit_status,
-	number_of_pages,
-	version,
-	is_all_security_to_be_removed,
-	is_encrypted,
-	stderr_blob
-    ) VALUES (
-    	'$UDIG',
-	$EXIT_STATUS,
-	$NUMBER_OF_PAGES,
-	$VERSION,
-	$IS_ALL_SECURITY_TO_BE_REMOVED,
-	$IS_ENCRYPTED,
-	$SQL_STDERR_BLOB
-    ) ON CONFLICT
-    	DO NOTHING
-;
-DELETE FROM pdfbox.pddocument_pending
-  WHERE
-  	blob = '$UDIG'
-;
-END TRANSACTION;
-
-EOF
-
-exit $EXIT_STATUS
+merge-stdin-pddocument_information 					\
+	$UDIG								\
+	$(file-stat-size $TMP_ROW) <$TMP_ROW				||
+	die "merge-stdin-pddocument_information failed: exit status=$?" 6
+exit 0
