stable, major refactor for blob/fault/service/rummy

diff --git a/schema/pdfbox/ssq-pdfbox-blob-count b/schema/pdfbox/ssq-pdfbox-blob-count
--- a/schema/pdfbox/ssq-pdfbox-blob-count
+++ b/schema/pdfbox/ssq-pdfbox-blob-count
@@ -1,17 +1,17 @@
 #!/usr/bin/env bash
 #
 #  Synopsis:
-#	List blobs in table pdfbox.blob
+#	Count blobs in table pdfbox.blob
 #
 source $SETSPACE_ROOT/lib/ssq-common.bash
 
 USAGE=''
 SQL=lib/$PROG.sql
-
 PSQL=$SSQ_COMMON_PSQL_TSV
 
 if [ $# = 0 ];  then
-	$PSQL --file $SQL || die "psql blob failed: exit status=$?"
+	$PSQL --file $SQL || die "psql blob count failed: exit status=$?"
 	exit 0
 fi
+
 exec_action $@
diff --git a/schema/pdfbox/ssq-pdfbox-fault b/schema/pdfbox/ssq-pdfbox-fault
--- a/schema/pdfbox/ssq-pdfbox-fault
+++ b/schema/pdfbox/ssq-pdfbox-fault
@@ -5,9 +5,12 @@
 #
 source $SETSPACE_ROOT/lib/ssq-common.bash
 
-USAGE=''
+USAGE='[count]'
 SQL=lib/$PROG.sql
-
 PSQL=$SSQ_COMMON_PSQL_TSV
 
-$PSQL --file $SQL || die "psql fault failed: exit status=$?"
+if [ $# = 0 ];  then
+	$PSQL --file $SQL || die "psql fault failed: exit status=$?"
+	exit 0
+fi
+exec_action $@
diff --git a/schema/pdfbox/ssq-pdfbox-rummy b/schema/pdfbox/ssq-pdfbox-rummy
--- a/schema/pdfbox/ssq-pdfbox-rummy
+++ b/schema/pdfbox/ssq-pdfbox-rummy
@@ -7,7 +7,11 @@ source $SETSPACE_ROOT/lib/ssq-common.bash
 
 USAGE=''
 SQL=lib/$PROG.sql
+	PSQL=$SSQ_COMMON_PSQL_TSV
 
-PSQL=$SSQ_COMMON_PSQL_TSV
+if [ $# = 0 ];  then
+	$PSQL --file $SQL || die "psql rummy failed: exit status=$?"
+	exit 0
+fi
 
-$PSQL --file $SQL || die "psql rummy failed: exit status=$?"
+exec_action $@
diff --git a/schema/pdfbox/ssq-pdfbox-service b/schema/pdfbox/ssq-pdfbox-service
--- a/schema/pdfbox/ssq-pdfbox-service
+++ b/schema/pdfbox/ssq-pdfbox-service
@@ -10,4 +10,9 @@ SQL=lib/$PROG.sql
 
 PSQL=$SSQ_COMMON_PSQL_TSV
 
-$PSQL --file $SQL || die "psql service failed: exit status=$?"
+if [ $# = 0 ];  then
+	$PSQL --file $SQL || die "psql service failed: exit status=$?"
+	exit 0
+fi
+
+exec_action $@
diff --git a/schema/pdfbox/ssq-pdfbox-service-count b/schema/pdfbox/ssq-pdfbox-service-count
--- a/schema/pdfbox/ssq-pdfbox-service-count
+++ b/schema/pdfbox/ssq-pdfbox-service-count
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 #
 #  Synopsis:
-#	List blobs in table pdfbox.blob
+#	Count blobs in view pdfbox.service
 #
 source $SETSPACE_ROOT/lib/ssq-common.bash
 
@@ -11,7 +11,8 @@ SQL=lib/$PROG.sql
 PSQL=$SSQ_COMMON_PSQL_TSV
 
 if [ $# = 0 ];  then
-	$PSQL --file $SQL || die "psql blob failed: exit status=$?"
+	$PSQL --file $SQL || die "psql service count failed: exit status=$?"
 	exit 0
 fi
+
 exec_action $@
diff --git a/schema/pdfbox/upsert-pddocument b/schema/pdfbox/upsert-pddocument
--- a/schema/pdfbox/upsert-pddocument
+++ b/schema/pdfbox/upsert-pddocument
@@ -15,8 +15,6 @@
 #  Note:
 #	Need to insure putPDDocument always writes utf8 and not utf16!
 #
-#	Need to upsert fault into flow file, instead of in this script.
-#
 
 PROG=upsert-pddocument
 PSQL='psql --no-psqlrc --quiet --no-readline --set=ON_ERROR_STOP=1'
@@ -31,8 +29,8 @@ leave()
 
 die()
 {
-	source $SETSPACE_SCHEMA_ROOT/lib/upsert-fault.bash
-	die_upsert upsert_pddocument $@
+	echo "$PROG: ERROR: $@" >&2
+	exit 2
 }
 
 jdie()
@@ -93,8 +91,7 @@ case $STATUS in
 	;;
 esac
 
-test $STATUS = 0							||
-	die "putPDDocument failed: exit status=$STATUS"
+test $STATUS = 0 || die "putPDDocument failed: exit status=$STATUS"
 test -s ROW || die 'ROW of putPDDocument is empty'
 
 #
